# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input

input {
# kb_layout = cz,jp,us,us_custom
# kb_variant = custom
    kb_file = ~/.config/xkb/custom.xkb
# kb_options="caps:swapescape"
# kb_layout = us,dk
        accel_profile = flat
        force_no_accel = true
        repeat_delay = 200
        sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}
